from cfonts import say


def main():
    say("Hello World!", colors=["red", "yellow"], align="center")
    say(
        'Generated by "cfonts"',
        space=False,
        font="console",
        colors=["gray"],
        background="green",
        align="center"
    )


if __name__ == "__main__":
    main()
